"""users table

Revision ID: 9ce0c48c9136
Revises: 
Create Date: 2018-12-05 03:39:13.921856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce0c48c9136'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('profilePic', sa.String(), nullable=True),
    sa.Column('receipts', sa.String(), nullable=True),
    sa.Column('creditCardNumber', sa.String(length=16), nullable=True),
    sa.Column('creditCardExpiration', sa.String(), nullable=True),
    sa.Column('creditCardCVC', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('creditCardNumber'),
    sa.UniqueConstraint('profilePic'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
